FROM /base/alpine-glibc:latest
ADD jdk-8u171-linux-x64.tar.gz /usr/local
RUN echo https://mirrors.aliyun.com/alpine/v3.7/main/ > /etc/apk/repositories && \
    echo https://mirrors.aliyun.com/alpine/v3.7/community/ >> /etc/apk/repositories
RUN apk update && apk upgrade

ENV JAVA_HOME=/usr/local/jdk1.8.0_171
ENV CLASSPATH=$JAVA_HOME/bin
ENV PATH=.:$JAVA_HOME/bin:$PATH
#CMD ["java","-version"]
