FROM /base/centos:7.4
ENV NVM_DIR /root/.nvm
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash \
    && source $NVM_DIR/nvm.sh \
    && nvm install 9.5.0 \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install pm2 -g

