FROM 192.168.210.10:8099/base/centos:7.4
RUN mkdir /data
RUN mkdir -p /etc/config/
RUN mkdir -p /etc/prometheus/console_libraries
RUN mkdir -p /etc/prometheus/consoles
COPY prometheus-2.3.1/console_libraries /etc/prometheus/console_libraries
COPY prometheus-2.3.1/consoles /etc/prometheus/consoles
COPY prometheus.yml /etc/config/prometheus.yml
COPY prometheus-2.3.1/prometheus /usr/local/bin/
COPY prometheus-2.3.1/promtool /usr/local/bin/
COPY change.sh /usr/local/bin/
#ENTRYPOINT ["/usr/local/bin/prometheus","--config.file","/etc/config/prometheus.yml","--storage.tsdb.path","/data","--web.console.libraries","/etc/prometheus/console_libraries","--web.console.templates","/etc/prometheus/consoles","--web.enable-lifecycle"]
ENTRYPOINT ["/usr/local/bin/prometheus","--config.file=/etc/config/prometheus.yml","--storage.tsdb.path=/data","--storage.tsdb.retention=7d","--web.console.libraries=/etc/prometheus/console_libraries","--web.console.templates=/etc/prometheus/consoles","--web.enable-lifecycle"]
