FROM 192./base/centos:7.4
RUN mkdir /data
COPY grafana-5.2.2-1.x86_64.rpm /root/
RUN yum -y localinstall /root/grafana-5.2.2-1.x86_64.rpm 
#CMD ["/root/grafana/bin/grafana-server","-homepath","/root/grafana"]
