#ENV SERVER_NAME="_"
#RUN /usr/bin/envsubst '$SERVER_NAME'< /home/git/nginx/conf.d/service.conf.template > /home/git/nginx/conf.d/service.conf
COPY mp-pkgdown-v20180815205315-10 /home/git/service/
CMD ["/etc/rc.d/rc.local"]
